'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsVentasMarengo
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GrowerDeal", [Namespace]:="MFC.WebService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GrowerDeal
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DealNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VendorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VendorCodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DealNumber() As String
            Get
                Return Me.DealNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DealNumberField, value) <> true) Then
                    Me.DealNumberField = value
                    Me.RaisePropertyChanged("DealNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vendor() As String
            Get
                Return Me.VendorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VendorField, value) <> true) Then
                    Me.VendorField = value
                    Me.RaisePropertyChanged("Vendor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VendorCode() As String
            Get
                Return Me.VendorCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VendorCodeField, value) <> true) Then
                    Me.VendorCodeField = value
                    Me.RaisePropertyChanged("VendorCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NetSales", [Namespace]:="MFC.WebService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class NetSales
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommodityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DealNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GradeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NetSalesMemberField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PackagingField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QtyField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SizeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalAdjustmentsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VarietyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VendorField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Commodity() As String
            Get
                Return Me.CommodityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommodityField, value) <> true) Then
                    Me.CommodityField = value
                    Me.RaisePropertyChanged("Commodity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Container() As String
            Get
                Return Me.ContainerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerField, value) <> true) Then
                    Me.ContainerField = value
                    Me.RaisePropertyChanged("Container")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DealNumber() As String
            Get
                Return Me.DealNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DealNumberField, value) <> true) Then
                    Me.DealNumberField = value
                    Me.RaisePropertyChanged("DealNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Grade() As String
            Get
                Return Me.GradeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GradeField, value) <> true) Then
                    Me.GradeField = value
                    Me.RaisePropertyChanged("Grade")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="NetSales")>  _
        Public Property NetSalesMember() As Decimal
            Get
                Return Me.NetSalesMemberField
            End Get
            Set
                If (Me.NetSalesMemberField.Equals(value) <> true) Then
                    Me.NetSalesMemberField = value
                    Me.RaisePropertyChanged("NetSalesMember")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Packaging() As String
            Get
                Return Me.PackagingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackagingField, value) <> true) Then
                    Me.PackagingField = value
                    Me.RaisePropertyChanged("Packaging")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostDate() As String
            Get
                Return Me.PostDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostDateField, value) <> true) Then
                    Me.PostDateField = value
                    Me.RaisePropertyChanged("PostDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Product() As String
            Get
                Return Me.ProductField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductField, value) <> true) Then
                    Me.ProductField = value
                    Me.RaisePropertyChanged("Product")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Qty() As Integer
            Get
                Return Me.QtyField
            End Get
            Set
                If (Me.QtyField.Equals(value) <> true) Then
                    Me.QtyField = value
                    Me.RaisePropertyChanged("Qty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Size() As String
            Get
                Return Me.SizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SizeField, value) <> true) Then
                    Me.SizeField = value
                    Me.RaisePropertyChanged("Size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalAdjustments() As Integer
            Get
                Return Me.TotalAdjustmentsField
            End Get
            Set
                If (Me.TotalAdjustmentsField.Equals(value) <> true) Then
                    Me.TotalAdjustmentsField = value
                    Me.RaisePropertyChanged("TotalAdjustments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Variety() As String
            Get
                Return Me.VarietyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VarietyField, value) <> true) Then
                    Me.VarietyField = value
                    Me.RaisePropertyChanged("Variety")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vendor() As String
            Get
                Return Me.VendorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VendorField, value) <> true) Then
                    Me.VendorField = value
                    Me.RaisePropertyChanged("Vendor")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransactionV2", [Namespace]:="http://schemas.datacontract.org/2004/07/IdentityLibrary.ProducePRO.Reports.Grower"& _ 
        "WebService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransactionV2
        Inherits wsVentasMarengo.Transaction
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnreceivedField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Unreceived() As Integer
            Get
                Return Me.UnreceivedField
            End Get
            Set
                If (Me.UnreceivedField.Equals(value) <> true) Then
                    Me.UnreceivedField = value
                    Me.RaisePropertyChanged("Unreceived")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Transaction", [Namespace]:="MFC.WebService"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(wsVentasMarengo.TransactionV2))>  _
    Partial Public Class Transaction
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BranchField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommodityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Cont_CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ContainerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private End_Of_DayField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FloorField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GradeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Grade_CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PackField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Pack2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PackagingField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReceivedField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RepackField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippedField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SizeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Size_CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UnpackField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VarField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VarietyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Vendor_Product_CodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Branch() As String
            Get
                Return Me.BranchField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BranchField, value) <> true) Then
                    Me.BranchField = value
                    Me.RaisePropertyChanged("Branch")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Commodity() As String
            Get
                Return Me.CommodityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommodityField, value) <> true) Then
                    Me.CommodityField = value
                    Me.RaisePropertyChanged("Commodity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cont_Code() As String
            Get
                Return Me.Cont_CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Cont_CodeField, value) <> true) Then
                    Me.Cont_CodeField = value
                    Me.RaisePropertyChanged("Cont_Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Container() As String
            Get
                Return Me.ContainerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ContainerField, value) <> true) Then
                    Me.ContainerField = value
                    Me.RaisePropertyChanged("Container")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property End_Of_Day() As Integer
            Get
                Return Me.End_Of_DayField
            End Get
            Set
                If (Me.End_Of_DayField.Equals(value) <> true) Then
                    Me.End_Of_DayField = value
                    Me.RaisePropertyChanged("End_Of_Day")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Floor() As Integer
            Get
                Return Me.FloorField
            End Get
            Set
                If (Me.FloorField.Equals(value) <> true) Then
                    Me.FloorField = value
                    Me.RaisePropertyChanged("Floor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Grade() As String
            Get
                Return Me.GradeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GradeField, value) <> true) Then
                    Me.GradeField = value
                    Me.RaisePropertyChanged("Grade")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Grade_Code() As String
            Get
                Return Me.Grade_CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Grade_CodeField, value) <> true) Then
                    Me.Grade_CodeField = value
                    Me.RaisePropertyChanged("Grade_Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pack() As String
            Get
                Return Me.PackField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackField, value) <> true) Then
                    Me.PackField = value
                    Me.RaisePropertyChanged("Pack")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pack2() As String
            Get
                Return Me.Pack2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Pack2Field, value) <> true) Then
                    Me.Pack2Field = value
                    Me.RaisePropertyChanged("Pack2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Packaging() As String
            Get
                Return Me.PackagingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PackagingField, value) <> true) Then
                    Me.PackagingField = value
                    Me.RaisePropertyChanged("Packaging")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Product() As String
            Get
                Return Me.ProductField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductField, value) <> true) Then
                    Me.ProductField = value
                    Me.RaisePropertyChanged("Product")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Received() As Integer
            Get
                Return Me.ReceivedField
            End Get
            Set
                If (Me.ReceivedField.Equals(value) <> true) Then
                    Me.ReceivedField = value
                    Me.RaisePropertyChanged("Received")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Repack() As Integer
            Get
                Return Me.RepackField
            End Get
            Set
                If (Me.RepackField.Equals(value) <> true) Then
                    Me.RepackField = value
                    Me.RaisePropertyChanged("Repack")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Shipped() As Integer
            Get
                Return Me.ShippedField
            End Get
            Set
                If (Me.ShippedField.Equals(value) <> true) Then
                    Me.ShippedField = value
                    Me.RaisePropertyChanged("Shipped")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Size() As String
            Get
                Return Me.SizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SizeField, value) <> true) Then
                    Me.SizeField = value
                    Me.RaisePropertyChanged("Size")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Size_Code() As String
            Get
                Return Me.Size_CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Size_CodeField, value) <> true) Then
                    Me.Size_CodeField = value
                    Me.RaisePropertyChanged("Size_Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Unpack() As Integer
            Get
                Return Me.UnpackField
            End Get
            Set
                If (Me.UnpackField.Equals(value) <> true) Then
                    Me.UnpackField = value
                    Me.RaisePropertyChanged("Unpack")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Var() As String
            Get
                Return Me.VarField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VarField, value) <> true) Then
                    Me.VarField = value
                    Me.RaisePropertyChanged("Var")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Variety() As String
            Get
                Return Me.VarietyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VarietyField, value) <> true) Then
                    Me.VarietyField = value
                    Me.RaisePropertyChanged("Variety")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vendor_Product_Code() As String
            Get
                Return Me.Vendor_Product_CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Vendor_Product_CodeField, value) <> true) Then
                    Me.Vendor_Product_CodeField = value
                    Me.RaisePropertyChanged("Vendor_Product_Code")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsVentasMarengo.IGrower")>  _
    Public Interface IGrower
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGrower/GetDeals", ReplyAction:="http://tempuri.org/IGrower/GetDealsResponse")>  _
        Function GetDeals(ByVal user As String, ByVal password As String) As wsVentasMarengo.GrowerDeal()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGrower/GetNetSales", ReplyAction:="http://tempuri.org/IGrower/GetNetSalesResponse")>  _
        Function GetNetSales(ByVal user As String, ByVal password As String, ByVal dealNumber As String, ByVal dateFrom As System.Nullable(Of Date), ByVal dateTo As System.Nullable(Of Date), ByVal groupBy As String) As wsVentasMarengo.NetSales()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGrower/GetGrowerTransactions", ReplyAction:="http://tempuri.org/IGrower/GetGrowerTransactionsResponse")>  _
        Function GetGrowerTransactions(ByVal user As String, ByVal password As String, ByVal dealNumber As String, ByVal dateTo As Date) As wsVentasMarengo.TransactionV2()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGrowerChannel
        Inherits wsVentasMarengo.IGrower, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GrowerClient
        Inherits System.ServiceModel.ClientBase(Of wsVentasMarengo.IGrower)
        Implements wsVentasMarengo.IGrower
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetDeals(ByVal user As String, ByVal password As String) As wsVentasMarengo.GrowerDeal() Implements wsVentasMarengo.IGrower.GetDeals
            Return MyBase.Channel.GetDeals(user, password)
        End Function
        
        Public Function GetNetSales(ByVal user As String, ByVal password As String, ByVal dealNumber As String, ByVal dateFrom As System.Nullable(Of Date), ByVal dateTo As System.Nullable(Of Date), ByVal groupBy As String) As wsVentasMarengo.NetSales() Implements wsVentasMarengo.IGrower.GetNetSales
            Return MyBase.Channel.GetNetSales(user, password, dealNumber, dateFrom, dateTo, groupBy)
        End Function
        
        Public Function GetGrowerTransactions(ByVal user As String, ByVal password As String, ByVal dealNumber As String, ByVal dateTo As Date) As wsVentasMarengo.TransactionV2() Implements wsVentasMarengo.IGrower.GetGrowerTransactions
            Return MyBase.Channel.GetGrowerTransactions(user, password, dealNumber, dateTo)
        End Function
    End Class
End Namespace
