//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8762
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("MFC.WebService", ClrNamespace="MFC.WebService")]

namespace MFC.WebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrowerDeal", Namespace="MFC.WebService")]
    public partial class GrowerDeal : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DealNumberField;
        
        private string DescriptionField;
        
        private string VendorField;
        
        private string VendorCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealNumber
        {
            get
            {
                return this.DealNumberField;
            }
            set
            {
                this.DealNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorCode
        {
            get
            {
                return this.VendorCodeField;
            }
            set
            {
                this.VendorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetSales", Namespace="MFC.WebService")]
    public partial class NetSales : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CommodityField;
        
        private string ContainerField;
        
        private string DealNumberField;
        
        private string GradeField;
        
        private decimal NetSalesMemberField;
        
        private string PackagingField;
        
        private string PostDateField;
        
        private string ProductField;
        
        private int QtyField;
        
        private string SizeField;
        
        private int TotalAdjustmentsField;
        
        private string VarietyField;
        
        private string VendorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commodity
        {
            get
            {
                return this.CommodityField;
            }
            set
            {
                this.CommodityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Container
        {
            get
            {
                return this.ContainerField;
            }
            set
            {
                this.ContainerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealNumber
        {
            get
            {
                return this.DealNumberField;
            }
            set
            {
                this.DealNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade
        {
            get
            {
                return this.GradeField;
            }
            set
            {
                this.GradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="NetSales")]
        public decimal NetSalesMember
        {
            get
            {
                return this.NetSalesMemberField;
            }
            set
            {
                this.NetSalesMemberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Packaging
        {
            get
            {
                return this.PackagingField;
            }
            set
            {
                this.PackagingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostDate
        {
            get
            {
                return this.PostDateField;
            }
            set
            {
                this.PostDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAdjustments
        {
            get
            {
                return this.TotalAdjustmentsField;
            }
            set
            {
                this.TotalAdjustmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variety
        {
            get
            {
                return this.VarietyField;
            }
            set
            {
                this.VarietyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor
        {
            get
            {
                return this.VendorField;
            }
            set
            {
                this.VendorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="MFC.WebService")]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BranchField;
        
        private string CommodityField;
        
        private string Cont_CodeField;
        
        private string ContainerField;
        
        private int End_Of_DayField;
        
        private int FloorField;
        
        private string GradeField;
        
        private string Grade_CodeField;
        
        private string PackField;
        
        private string Pack2Field;
        
        private string PackagingField;
        
        private string ProductField;
        
        private int ReceivedField;
        
        private int RepackField;
        
        private int ShippedField;
        
        private string SizeField;
        
        private string Size_CodeField;
        
        private int UnpackField;
        
        private string VarField;
        
        private string VarietyField;
        
        private string Vendor_Product_CodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Branch
        {
            get
            {
                return this.BranchField;
            }
            set
            {
                this.BranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commodity
        {
            get
            {
                return this.CommodityField;
            }
            set
            {
                this.CommodityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cont_Code
        {
            get
            {
                return this.Cont_CodeField;
            }
            set
            {
                this.Cont_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Container
        {
            get
            {
                return this.ContainerField;
            }
            set
            {
                this.ContainerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int End_Of_Day
        {
            get
            {
                return this.End_Of_DayField;
            }
            set
            {
                this.End_Of_DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade
        {
            get
            {
                return this.GradeField;
            }
            set
            {
                this.GradeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade_Code
        {
            get
            {
                return this.Grade_CodeField;
            }
            set
            {
                this.Grade_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pack
        {
            get
            {
                return this.PackField;
            }
            set
            {
                this.PackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pack2
        {
            get
            {
                return this.Pack2Field;
            }
            set
            {
                this.Pack2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Packaging
        {
            get
            {
                return this.PackagingField;
            }
            set
            {
                this.PackagingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Received
        {
            get
            {
                return this.ReceivedField;
            }
            set
            {
                this.ReceivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Repack
        {
            get
            {
                return this.RepackField;
            }
            set
            {
                this.RepackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shipped
        {
            get
            {
                return this.ShippedField;
            }
            set
            {
                this.ShippedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Size_Code
        {
            get
            {
                return this.Size_CodeField;
            }
            set
            {
                this.Size_CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Unpack
        {
            get
            {
                return this.UnpackField;
            }
            set
            {
                this.UnpackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var
        {
            get
            {
                return this.VarField;
            }
            set
            {
                this.VarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variety
        {
            get
            {
                return this.VarietyField;
            }
            set
            {
                this.VarietyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vendor_Product_Code
        {
            get
            {
                return this.Vendor_Product_CodeField;
            }
            set
            {
                this.Vendor_Product_CodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGrower")]
public interface IGrower
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrower/GetDeals", ReplyAction="http://tempuri.org/IGrower/GetDealsResponse")]
    MFC.WebService.GrowerDeal[] GetDeals(string user, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrower/GetNetSales", ReplyAction="http://tempuri.org/IGrower/GetNetSalesResponse")]
    MFC.WebService.NetSales[] GetNetSales(string user, string password, string dealNumber, System.Nullable<System.DateTime> dateFrom, System.Nullable<System.DateTime> dateTo, string groupBy);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrower/GetGrowerTransactions", ReplyAction="http://tempuri.org/IGrower/GetGrowerTransactionsResponse")]
    MFC.WebService.Transaction[] GetGrowerTransactions(string user, string password, string dealNumber, System.DateTime dateTo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IGrowerChannel : IGrower, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GrowerClient : System.ServiceModel.ClientBase<IGrower>, IGrower
{
    
    public GrowerClient()
    {
    }
    
    public GrowerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GrowerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GrowerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GrowerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MFC.WebService.GrowerDeal[] GetDeals(string user, string password)
    {
        return base.Channel.GetDeals(user, password);
    }
    
    public MFC.WebService.NetSales[] GetNetSales(string user, string password, string dealNumber, System.Nullable<System.DateTime> dateFrom, System.Nullable<System.DateTime> dateTo, string groupBy)
    {
        return base.Channel.GetNetSales(user, password, dealNumber, dateFrom, dateTo, groupBy);
    }
    
    public MFC.WebService.Transaction[] GetGrowerTransactions(string user, string password, string dealNumber, System.DateTime dateTo)
    {
        return base.Channel.GetGrowerTransactions(user, password, dealNumber, dateTo);
    }
}
